### ISSUE TITLE
Tests not found

### ISSUE THREAD

**Issue by ntzrbtr** [eWert-Online/OSnap#27]
This is my config:

``` yaml
---
baseUrl: https://xyz.com/
fullScreen: true
threshold: 3
parallelism: 10
testPattern: "./visual-regression-tests/**/*.osnap.yaml"
snapshotDirectory: "./snapshots/live/"
defaultSizes:
    -   name: xxl
        width: 1600
        height: 900
    -   name: xl
        width: 1366
        height: 768
    -   name: md
        width: 1024
        height: 576
    -   name: sm
        width: 768
        height: 432
    -   name: xs
        width: 640
        height: 360
    -   name: xxs
        width: 320
        height: 180
```

My first test is placed in file "visual-regression-tests/home.osnap.yaml", but the tool does not find the test. What am I doing wrong?
